#!/bin/bash 

status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $status = "Charging" ]; then
    charge=""
else
    charge=""
fi
if [ $capacity -gt 80 ]; then
    symbol=""
elif [ $capacity -gt 50 ]; then
    symbol=""
elif [ $capacity -gt 25 ]; then
    symbol=""
elif [ $capacity -gt 10 ]; then
    symbol=""
else
    symbol=""
fi
echo -e " ${symbol} ${charge}${capacity}% "
